/*
 * Courier API Reference
 *
 * The Courier REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@courier.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Com.Courier.Client;
using Com.Courier.Api;
// uncomment below to import models
//using Com.Courier.Model;

namespace Com.Courier.Test.Api
{
    /// <summary>
    ///  Class for testing SendAPIApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SendAPIApiTests : IDisposable
    {
        private SendAPIApi instance;

        public SendAPIApiTests()
        {
            instance = new SendAPIApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendAPIApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SendAPIApi
            //Assert.IsType<SendAPIApi>(instance);
        }

        /// <summary>
        /// Test SendPost
        /// </summary>
        [Fact]
        public void SendPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Send send = null;
            //var response = instance.SendPost(send);
            //Assert.IsType<InlineResponse200>(response);
        }
    }
}
