/*
 * Courier API Reference
 *
 * The Courier REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@courier.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Courier.Api;
using Com.Courier.Model;
using Com.Courier.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Courier.Test.Model
{
    /// <summary>
    ///  Class for testing Paging
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PagingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Paging
        //private Paging instance;

        public PagingTests()
        {
            // TODO uncomment below to create an instance of Paging
            //instance = new Paging();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Paging
        /// </summary>
        [Fact]
        public void PagingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Paging
            //Assert.IsType<Paging>(instance);
        }


        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }
        /// <summary>
        /// Test the property 'More'
        /// </summary>
        [Fact]
        public void MoreTest()
        {
            // TODO unit test for the property 'More'
        }

    }

}
