/*
 * Courier API Reference
 *
 * The Courier REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@courier.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Courier.Api;
using Com.Courier.Model;
using Com.Courier.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Courier.Test.Model
{
    /// <summary>
    ///  Class for testing PartialMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartialMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartialMessage
        //private PartialMessage instance;

        public PartialMessageTests()
        {
            // TODO uncomment below to create an instance of PartialMessage
            //instance = new PartialMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartialMessage
        /// </summary>
        [Fact]
        public void PartialMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartialMessage
            //Assert.IsType<PartialMessage>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Enqueued'
        /// </summary>
        [Fact]
        public void EnqueuedTest()
        {
            // TODO unit test for the property 'Enqueued'
        }
        /// <summary>
        /// Test the property 'Sent'
        /// </summary>
        [Fact]
        public void SentTest()
        {
            // TODO unit test for the property 'Sent'
        }
        /// <summary>
        /// Test the property 'Delivered'
        /// </summary>
        [Fact]
        public void DeliveredTest()
        {
            // TODO unit test for the property 'Delivered'
        }
        /// <summary>
        /// Test the property 'Opened'
        /// </summary>
        [Fact]
        public void OpenedTest()
        {
            // TODO unit test for the property 'Opened'
        }
        /// <summary>
        /// Test the property 'Clicked'
        /// </summary>
        [Fact]
        public void ClickedTest()
        {
            // TODO unit test for the property 'Clicked'
        }
        /// <summary>
        /// Test the property 'Recipient'
        /// </summary>
        [Fact]
        public void RecipientTest()
        {
            // TODO unit test for the property 'Recipient'
        }
        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'Notification'
        /// </summary>
        [Fact]
        public void NotificationTest()
        {
            // TODO unit test for the property 'Notification'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

    }

}
